
###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?sender=Maya

###

GET http://localhost:3000/posts/6777be3b5d9bfaed4c7c1ee0

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Test",
    "senderID": "Maya",
    "content": "This is a test"
}

###

PUT http://localhost:3000/posts/6777be3b5d9bfaed4c7c1ee0
Content-Type: application/json

{
    "senderID":123,
    "content":"this is a test number 2",
    "title":"test"
} 

###

GET http://localhost:3000/comments

###

GET http://localhost:3000/comments/6777be6b5d9bfaed4c7c1ee7

###

GET http://localhost:3000/comments?post=6777be3b5d9bfaed4c7c1ee0

###

POST http://localhost:3000/comments
Content-Type: application/json

{
  "postsID": "6777be3b5d9bfaed4c7c1ee0",
  "content": "wow",
  "senderID": "4567"
}

###

PUT http://localhost:3000/comments/6777be6b5d9bfaed4c7c1ee7
Content-Type: application/json

{
  "content": "wow this is amazing",
  "senderID": "4567"
}

###

DELETE http://localhost:3000/comments/6777be6b5d9bfaed4c7c1ee7

###


